import Rx from "rxjs";
import createState from "app/rx-state/createState";
import CounterReducer$ from "app/reducers/CounterReducer";
import TodoListReducer$ from "app/reducers/TodoListReducer";



const reducer$ = Rx.Observable.merge(
  CounterReducer$,
  TodoListReducer$
);

const initialState$ = Rx.Observable.of({
  counter: 0,
  todos: {
    items: [
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false}
       ,
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},
      {label: 'Сегодня всё получается медленно', checked: false, editMode: false},
      {label: 'тестовая HALLO запись', checked: true, editMode: false},
      {label: 'тестовая запись2', checked: false, editMode: false},
      {label: 'И еще что-то', checked: false, editMode: false},

    ]
  }
});

export default createState(reducer$, initialState$);
