import Rx from "rxjs";
import createState from "app/rx-state/createState";
import todoReducer$ from "app/reducers/todoReducer";
import automation from "app/rx-state/automation";



const reducer$ = Rx.Observable.merge(
  todoReducer$
);

const initialState$ = Rx.Observable.of({
  counter: 0,
  todos: {
    toggleAll: false,
    newTodoValue: '',
    items: [
               {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},


      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},
      {label: 'тестовая HALLO запись', checked: true, restoreLabel: ''},
      {label: 'тестовая запись2', checked: false, restoreLabel: ''},
      {label: 'И еще что-то', checked: false, restoreLabel: ''},
      {label: 'Сегодня всё получается медленно', checked: false, restoreLabel: ''},

    ]
  }
});
var state$ = automation(createState(reducer$, initialState$));



//state$.subscribe(r=>{console.log(r.todos.items[0])});

export default state$;
